# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs





name: Node.js CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: test
      run: |
        echo ${{ matrix.version }}
        sudo apt-get update && sudo apt-get -y install libsoup3.0-0 woff2 libvpx7 libevent-2.1-7 libopus0 libharfbuzz-icu0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgst-plugins-bad1.0-0 libgst-plugins-good1.0-0 libgst-plugins-ugly1.0-0 libgst-plugins-base1.0-0 libgst-plugins-base1.0-dev libgst-plugins-base1.0-doc libgst-plugins-base1.0-tools libgst-plugins-base1.0-dev libgst-plugins-base1.0-doc libgst-plugins-base1.0-tools libhyphen0 libmanette0.2-0 libflite1 libflite-usenglish libflite-cmu-grapheme-lang libflite-cmu-grapheme-lex libflite-cmu-indic-lang libflite-cmu-indic-lex libflite-cmulex libflite-cmu-time-awb libflite-cmu-us-awb libflite-cmu-us-kal16 libflite-cmu-us-kal libflite-cmu-us-rms libflite-cmu-us-slt libgles2 libx264-155
        npm ci
        npx playwright install
        xvfb-run node index.js








